<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250820093520 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Vytvoření tabulek pro FAQ systém: faq_categories, faqs a vazební tabulka faq_faq_categories';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE faq_categories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, color VARCHAR(7) DEFAULT NULL, order_index INT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FB1174E4989D9B62 ON faq_categories (slug)');
        $this->addSql('CREATE TABLE faqs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, question VARCHAR(500) NOT NULL, answer TEXT NOT NULL, slug VARCHAR(100) NOT NULL, order_index INT NOT NULL, is_active BOOLEAN NOT NULL, view_count INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8934BEE5989D9B62 ON faqs (slug)');
        $this->addSql('CREATE TABLE faq_faq_categories (faq_id INT NOT NULL, faq_category_id INT NOT NULL, PRIMARY KEY (faq_id, faq_category_id))');
        $this->addSql('CREATE INDEX IDX_FB5A2FD181BEC8C2 ON faq_faq_categories (faq_id)');
        $this->addSql('CREATE INDEX IDX_FB5A2FD1F689B0DB ON faq_faq_categories (faq_category_id)');
        $this->addSql('ALTER TABLE faq_faq_categories ADD CONSTRAINT FK_FB5A2FD181BEC8C2 FOREIGN KEY (faq_id) REFERENCES faqs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE faq_faq_categories ADD CONSTRAINT FK_FB5A2FD1F689B0DB FOREIGN KEY (faq_category_id) REFERENCES faq_categories (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE faq_faq_categories DROP CONSTRAINT FK_FB5A2FD181BEC8C2');
        $this->addSql('ALTER TABLE faq_faq_categories DROP CONSTRAINT FK_FB5A2FD1F689B0DB');
        $this->addSql('DROP TABLE faq_categories');
        $this->addSql('DROP TABLE faqs');
        $this->addSql('DROP TABLE faq_faq_categories');
    }
}
