<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250902123104 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Vytvoření tabulek card_blocks a cards pro CardBlock komponentu';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE card_blocks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE cards (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image VARCHAR(255) NOT NULL, title VARCHAR(200) NOT NULL, text VARCHAR(500) NOT NULL, link_url VARCHAR(255) NOT NULL, order_index INT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, card_block_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C258FD50DC4C8F ON cards (card_block_id)');
        $this->addSql('ALTER TABLE cards ADD CONSTRAINT FK_4C258FD50DC4C8F FOREIGN KEY (card_block_id) REFERENCES card_blocks (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cards DROP CONSTRAINT FK_4C258FD50DC4C8F');
        $this->addSql('DROP TABLE card_blocks');
        $this->addSql('DROP TABLE cards');
    }
}
